### ISSUE TITLE
Eleventy build issue with posts that have setted tags 

### ISSUE THREAD

**Issue by laurent-d** [liamfiddler/eleventy-plugin-lazyimages#31]
Hi @liamfiddler,

Thanks for your great work on your plugin.
I have some issues with the plugin when i set tags to my posts.
Tags are setted with a post.json file on the directory like that :
{
    "tags": [
      "posts"
    ]
  }

I'm running the site with the last version of 11ty (v11) and your plugin..

Logs :

`TemplateWriterWriteError` was thrown
> Cannot read property 'toLowerCase' of undefined

`TypeError` was thrown:
    TypeError: Cannot read property 'toLowerCase' of undefined
        at processImage (/Users/laurentdelacerda/une-architecture/node_modules/eleventy-plugin-lazyimages/.eleventy.js:150:45)
        at Promise.all.images.map (/Users/laurentdelacerda/une-architecture/node_modules/eleventy-plugin-lazyimages/.eleventy.js:198:47)
        at Array.map (<anonymous>)
        at Template.transformMarkup (/Users/laurentdelacerda/une-architecture/node_modules/eleventy-plugin-lazyimages/.eleventy.js:198:32)
        at Template.runTransforms (/Users/laurentdelacerda/.nvm/versions/node/v10.19.0/lib/node_modules/@11ty/eleventy/src/Template.js:369:29)
        at Template.renderPageEntry (/Users/laurentdelacerda/.nvm/versions/node/v10.19.0/lib/node_modules/@11ty/eleventy/src/Template.js:609:26)
        at process._tickCallback (internal/process/next_tick.js:68:7)

Someone has this issue ?
Without the plugin all is fine.

Laurent

**Comment by laurent-d** [comment]
If i comment the line 150 on .eleventy.js of the plugin ...

  // if (!supportedExtensions.includes(fileExt.toLowerCase())) {
  //   logMessage(`${fileExt} placeholder not supported: ${imgPath}`);
  //   return;
  // }

All is fine again

**Comment by liamfiddler** [comment]
👋 Hi @laurent-d 

Thanks for raising this, and for using the plugin.

Can you confirm the issue only happens when tags are added to your posts? The error message and your commented out code suggests `fileExt` is undefined.

Is there a code repo or example I could look at?

**Comment by MaybeThisIsRu** [comment]
> If i comment the line 150 on .eleventy.js of the plugin ...
> 
> // if (!supportedExtensions.includes(fileExt.toLowerCase())) {
> // logMessage(`${fileExt} placeholder not supported: ${imgPath}`);
> // return;
> // }
> 
> All is fine again

Are you using any image with an address/file path that does not have an extension? I had such an issue with an HTTP URL. Good to double check.

**Comment by liamfiddler** [comment]
🚀 We've just released [version 2.1 of this plugin](https://www.npmjs.com/package/eleventy-plugin-lazyimages#v210) which better handles file paths without an extension, and no longer preemptively skips files without an extension. It should resolve this issue.

(I'll close this issue for now, but feel free to reopen it if the problem persists)
