### ISSUE TITLE
Trouble installing this plugin, seems to be issue with 'sharp'

### ISSUE THREAD

**Issue by khoivan88** [liamfiddler/eleventy-plugin-lazyimages#40]
Hi, thank you for this very useful library. I have been using this library for a while and it has been working great till I updated to the latest version using sharp. I think there is some issue with npm installing sharp on my computer. Perhaps because there are spaces in some of my folders' names?

This is the npm error:

```shell
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.3.0/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'rebuild',
0 verbose cli   '--verbose',
0 verbose cli   'sharp'
0 verbose cli ]
1 info using npm@7.0.14
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 3ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2/.npmrc Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/[name]/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 12ms
19 verbose npm-session 0a3d80290757922c
20 timing npm:load Completed in 106ms
21 timing arborist:ctor Completed in 1ms
22 timing arborist:ctor Completed in 0ms
23 timing build:queue Completed in 4ms
24 info run sharp@0.25.4 install node_modules/sharp (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
25 info run sharp@0.25.4 install { code: 1, signal: null }
26 timing command:rebuild Completed in 9186ms
27 verbose stack Error: command failed
27 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
27 verbose stack     at ChildProcess.emit (node:events:376:20)
27 verbose stack     at maybeClose (node:internal/child_process:1055:16)
27 verbose stack     at Socket.<anonymous> (node:internal/child_process:441:11)
27 verbose stack     at Socket.emit (node:events:376:20)
27 verbose stack     at Pipe.<anonymous> (node:net:661:12)
28 verbose pkgid sharp@0.25.4
29 verbose cwd /Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2
30 verbose Darwin 17.7.0
31 verbose argv "/usr/local/Cellar/node/15.3.0/bin/node" "/usr/local/bin/npm" "rebuild" "--verbose" "sharp"
32 verbose node v15.3.0
33 verbose npm  v7.0.14
34 error code 1
35 error path /Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2/node_modules/sharp
36 error command failed
37 error command sh -c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
38 error cc -o Release/obj.target/nothing/../node-addon-api/nothing.o ../../node-addon-api/nothing.c '-DNODE_GYP_MODULE_NAME=nothing' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' -I/Users/[name]/Library/Caches/node-gyp/15.3.0/include/node -I/Users/[name]/Library/Caches/node-gyp/15.3.0/src -I/Users/[name]/Library/Caches/node-gyp/15.3.0/deps/openssl/config -I/Users/[name]/Library/Caches/node-gyp/15.3.0/deps/openssl/openssl/include -I/Users/[name]/Library/Caches/node-gyp/15.3.0/deps/uv/include -I/Users/[name]/Library/Caches/node-gyp/15.3.0/deps/zlib -I/Users/[name]/Library/Caches/node-gyp/15.3.0/deps/v8/include  -O3 -gdwarf-2 -mmacosx-version-min=10.13 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/nothing/../node-addon-api/nothing.o.d.raw   -c
38 error   rm -f Release/nothing.a && ./gyp-mac-tool filter-libtool libtool  -static -o Release/nothing.a Release/obj.target/nothing/../node-addon-api/nothing.o
38 error   touch Release/obj.target/libvips-cpp.stamp
38 error   c++ -o Release/obj.target/sharp/src/common.o ../src/common.cc '-DNODE_GYP_MODULE_NAME=sharp' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DNAPI_VERSION=3' '-DBUILDING_NODE_EXTENSION' -I/Users/[name]/Library/Caches/node-gyp/15.3.0/include/node -I/Users/[name]/Library/Caches/node-gyp/15.3.0/src -I/Users/[name]/Library/Caches/node-gyp/15.3.0/deps/openssl/config -I/Users/[name]/Library/Caches/node-gyp/15.3.0/deps/openssl/openssl/include -I/Users/[name]/Library/Caches/node-gyp/15.3.0/deps/uv/include -I/Users/[name]/Library/Caches/node-gyp/15.3.0/deps/zlib -I/Users/[name]/Library/Caches/node-gyp/15.3.0/deps/v8/include -I/Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2/node_modules/node-addon-api -I../vendor/include -I../vendor/include/glib-2.0 -I../vendor/lib/glib-2.0/include  -O3 -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fexceptions -Wall -O3 -MMD -MF ./Release/.deps/Release/obj.target/sharp/src/common.o.d.raw   -c
39 error info sharp Using existing vendored libvips v8.9.1
39 error prebuild-install info begin Prebuild-install version 5.3.6
39 error prebuild-install info install installing standalone, skipping download.
39 error gyp info it worked if it ends with ok
39 error gyp verb cli [
39 error gyp verb cli   '/usr/local/Cellar/node/15.3.0/bin/node',
39 error gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
39 error gyp verb cli   'rebuild'
39 error gyp verb cli ]
39 error gyp info using node-gyp@7.1.2
39 error gyp info using node@15.3.0 | darwin | x64
39 error gyp verb command rebuild []
39 error gyp verb command clean []
39 error gyp verb clean removing "build" directory
39 error gyp verb command configure []
39 error gyp verb find Python Python is not set from command line or npm configuration
39 error gyp verb find Python Python is not set from environment variable PYTHON
39 error gyp verb find Python checking if "python3" can be used
39 error gyp verb find Python - executing "python3" to get executable path
39 error gyp verb find Python - executable path is "/Users/[name]/.pyenv/versions/3.9.0/bin/python3"
39 error gyp verb find Python - executing "/Users/[name]/.pyenv/versions/3.9.0/bin/python3" to get version
39 error gyp verb find Python - version is "3.9.0"
39 error gyp info find Python using Python version 3.9.0 found at "/Users/[name]/.pyenv/versions/3.9.0/bin/python3"
39 error gyp verb get node dir no --target version specified, falling back to host node version: 15.3.0
39 error gyp verb command install [ '15.3.0' ]
39 error gyp verb install input version string "15.3.0"
39 error gyp verb install installing version: 15.3.0
39 error gyp verb install --ensure was passed, so won't reinstall if already installed
39 error gyp verb install version is already installed, need to check "installVersion"
39 error gyp verb got "installVersion" 9
39 error gyp verb needs "installVersion" 9
39 error gyp verb install version is good
39 error gyp verb get node dir target node version installed: 15.3.0
39 error gyp verb build dir attempting to create "build" dir: /Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2/node_modules/sharp/build
39 error gyp verb build dir "build" dir needed to be created? /Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2/node_modules/sharp/build
39 error gyp verb build/config.gypi creating config file
39 error gyp verb build/config.gypi writing out config file: /Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2/node_modules/sharp/build/config.gypi
39 error gyp verb config.gypi checking for gypi file: /Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2/node_modules/sharp/config.gypi
39 error gyp verb common.gypi checking for gypi file: /Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2/node_modules/sharp/common.gypi
39 error gyp verb gyp gyp format was not specified; forcing "make"
39 error gyp info spawn /Users/[name]/.pyenv/versions/3.9.0/bin/python3
39 error gyp info spawn args [
39 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
39 error gyp info spawn args   'binding.gyp',
39 error gyp info spawn args   '-f',
39 error gyp info spawn args   'make',
39 error gyp info spawn args   '-I',
39 error gyp info spawn args   '/Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2/node_modules/sharp/build/config.gypi',
39 error gyp info spawn args   '-I',
39 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
39 error gyp info spawn args   '-I',
39 error gyp info spawn args   '/Users/[name]/Library/Caches/node-gyp/15.3.0/include/node/common.gypi',
39 error gyp info spawn args   '-Dlibrary=shared_library',
39 error gyp info spawn args   '-Dvisibility=default',
39 error gyp info spawn args   '-Dnode_root_dir=/Users/[name]/Library/Caches/node-gyp/15.3.0',
39 error gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
39 error gyp info spawn args   '-Dnode_lib_file=/Users/[name]/Library/Caches/node-gyp/15.3.0/<(target_arch)/node.lib',
39 error gyp info spawn args   '-Dmodule_root_dir=/Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2/node_modules/sharp',
39 error gyp info spawn args   '-Dnode_engine=v8',
39 error gyp info spawn args   '--depth=.',
39 error gyp info spawn args   '--no-parallel',
39 error gyp info spawn args   '--generator-output',
39 error gyp info spawn args   'build',
39 error gyp info spawn args   '-Goutput_dir=.'
39 error gyp info spawn args ]
39 error gyp verb command build []
39 error gyp verb build type Release
39 error gyp verb architecture x64
39 error gyp verb node dev dir /Users/[name]/Library/Caches/node-gyp/15.3.0
39 error gyp verb `which` succeeded for `make` /usr/bin/make
39 error gyp info spawn make
39 error gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
39 error clang: error: no such file or directory: [part-of-folder-name-with-spaces]
39 error clang: error: no such file or directory: [part-of-folder-name-with-spaces]
39 error clang: error: no such file or directory: [part-of-folder-name-with-spaces]
39 error clang: error: no such file or directory: '[part-of-folder-name-with-spaces]/Documents/Learning/misc/organicchemistrydata-v2/node_modules/node-addon-api'
39 error make: *** [Release/obj.target/sharp/src/common.o] Error 1
39 error gyp ERR! build error
39 error gyp ERR! stack Error: `make` failed with exit code: 2
39 error gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
39 error gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
39 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
39 error gyp ERR! System Darwin 17.7.0
39 error gyp ERR! command "/usr/local/Cellar/node/15.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
39 error gyp ERR! cwd /Users/[name]/[path with folder names containing spaces]/Documents/Learning/misc/organicchemistrydata-v2/node_modules/sharp
39 error gyp ERR! node -v v15.3.0
39 error gyp ERR! node-gyp -v v7.1.2
39 error gyp ERR! not ok
40 verbose exit 1
```

**Update**: I can install 'sharp' (`npm i sharp -D`) just fine!

I was just wondering if you might have any suggestion for me to fix this issue? Thank you very much!!

**Comment by khoivan88** [comment]
This should be a problem when installing on path with folder names containing space. Should be fixed now with #41
